---
title: "Blockchain and the Constitution of a New Financial Order: Legal and Political Challenges"
author: "Adam Slack"
date: "19 June 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Panel 1: THe Law and Technology of blockchain -- An Overview
+ Paolo Tasca (UCL) -- *Technical and Legal business challenges of Blockchain Enabled Systems*
+ Tomaso Aste (UCL) -- *What is truth? Blokchain technology and history by majority consensus*
+ Ioannis Lianos (UCL) -- *Law, Fintech and the performative turn in regulation*
+ Karen Yeung (Kings College London) -- *Governence by Blockchain: THe upcoming battle for supremacy between the code of law vs the code as law.*
+ Giovanni Sartor (European University Institute) -- *Semantics and Pragmatics of self-enforcing laws and contracts*

# Paolo Tasca (UCL) -- *Technical and Legal business challenges of Blockchain Enabled Systems*
## Challenges
+ General Challenges
+ Legal and regulatory challenges
+ Technical Challenges
+ Business challenges
There is overlap between each of these areas

## Multidimensional Challenges
Underdeveloped ecosystem
- Adoption of a blockchain is necessary but not enough
- need a whole ecosystem of stakeholders focused around the adoption of such a technology
- Complete Tech stacks.
- analysts
- users
  
## Multidimensional Challenges
Lack of educated individuals
- Niche area, means very limited amount software developers
- Mid 2016 there were appox. 5000 developers
- Compare the number to Java at approx 18.5 million developers
- Lack of educated individuals at an executive level.


## Multidimensional Challenges
Lack of Standards
+ Standards arrive as 
    - De-facto virtue of market adoption
    - Via organisations puting standards into place
+ Standards will introduce many aspects
    - Increased adoption
    - Interoperability
    - Lower costs and less overall risks
+ Standards also help with other topics
    - Use cases
    - Terminology, taxonomy, ontology and reference architecture.
            

## Multidimensional Challenges            
Blockchain is a foundational technology 
- it will take a long time for wide spread adoption
- Relies on a 'kiler app' and such like development to really push the technology
    

## Legal and Regulatory Challenges
Uncertain regulatory status

- Paradigm shifts

- Regulation, yes -- better later than never

What can be done to reduce regulatory unsertainty?

- The uncertainty is normal, its a new technology.
    
## Legal and Regulatory Challenges
Political/governmental intervention
- Political vision of the current 4IR (what is 4IR???)

- Internet of value -- dont want to reduce the value that such technology can have

- Consumer Protection

- Lacking a clear understanding that this is the next industrial revolution.

- Many new challenges from a consumer perspective.
    

## Business Challenges
Survey of businesses
Most Important | Most Difficult
---------------|----------------
Legal Challenges | Legal Challenges
Business Challenges | Technical Challenges
Technical Challenges | Business Challenges

# Tomaso Aste (UCL): What is truth? Blockchain Technology and history by majority consensus

## The Trust Machine
True to some extent
- Verified by large communities
- Hard to tamper with purely cause of size and decentralised nature
- Verified recorded immutable history of fair-play, gives reputation to involved agents.
  
No need for trusted intermediaries

## Blochchain
 - Google 'structre of blockchain', cba to type it out.
 
## origins of blockchain
- Started with Hash trees (merkle trees) and hash chains
- Got to electronic hash chain payments in the 90s
- Proof of work via Hash Cash
- Bitcoin came around after (2008)


## Distribution + Community Consensus = Trues
- Consensus => transparency
- Consensus => Truth decided by community majority
- Consensus => History is probabilistic

# All Truth within the system is by consensus
- Not necessarily the Truth, just the aggreed one.
- The consensus can very well be wrong.
- Generating Hashes doesn't necessarily validate truth.
    - Just that is accepted as having happend
    - Then its completely immutable
    - For storing information, this means that lies can be immutably stored.
    
## Consensus comes with a cost
- There a lot of insentive to alter the truth
- It costs the community a lot of computing power to ensure validity is maintained
- (note: this only applies to proof of work, proof of stake would make it a monetary issue)


## Challenges
- Efficiency and scalability
- Legal implications for code misbehaviour
    - Some code may even be automatically generated wihin a distributed and unsupervised system
    - Who is responsible
    - Who will regulate/supervise

## Challenges
- Can we afford to keep immutable historic records
    - Probably not
    - What if there is a war
    - What if there are criminal organisations?

- Can blockchains be made future proof
    - Preserve integrity
    - In the future current cryptographic technology will likely be broken
    
    
# Ioannis Lianos (UCL) -- Law, Fintech and the perfomative turn in regulation

## Drastic and Disruptive innovation
- bitcoin -- one of the first successful applicaitons of a distrubuted ledger 
- bitcoin 2.0 -- to store all kinds of information
- ethereum -- software platform for the development and deployment of all kinds of decentalised applications

## blockchain and fintech
5 principals underlying the technology
- Distributed database
- P2P transmission
- Transparency with pseudonymity
- Immutability of records
- Comutational logic
    
- Fintech is the amalgomation of finance and technology.

## Regulators -- promoting competition and innovation
- Financial conduct authority - promote effective competition in the interest of consumers
- Payment systems regulator - specific interests relating to the payment sector. promote insterests of users and services provided by payment systems.

## Regulatory Initiatives
- FCA -- project Innovate
- Regulatory Sandbox -- A sandbox from which businesses have a 'safe space' to experiement with new technology.
    - This can be used to introduce unauthorised businesses to the market
    - Allows regulatory authorities to test the impact of new regulations.
- Regulation becomes a collaboration industry
    - Bespoke regulatory rules
  
## Payment system regulators
- Heavily interested in blockchain technology
- Bank of England -- regulatory investigations
    - Research Hub
    - FinTech Accelerator
- Prudential Regulatoryt Authority


## Rules vs prinicals base
- Principals based regulation promotes collaboration
    - Authorities state what they want to achieve
    - Leads to Algorithmic Regulation
    - Lean regulation
    - Agile regulation
    
    
## Platforms vs Blockchain
- Blockchain aren't platforms
- OpenBazaar, Amazon, Google
- Competition between existing platforms to produce their own system.

## OpenBazaar and markets
Will it lead to a wide open competative market?

- Still an issue with centralised groups of hashing teams
- These groups will be competative
    - still not down to the individuals

## Lack of quantitiative measurements for innovation
- As regulatory authories lack methods of quantifying the promotion of innovaiton
    - regarding its success at least
    
- performative regulation will take be more prominent
    - this measn more interaction and involvment between regulators and businesses.


#Karen Yeung -  *Governence by blockchain: the coming battle for supremacy between code of law vs code as law.*
## Introduction

- Explore the intersection and interactions of conventional law and internal rules of blockchain systems

- How success will 'governance by blockchain' be at avoding governance by conventional law?

- Algorithmic Governence
    - predictive analytics and automated decision making systems
    - distributed ledger systems.

- Focus on developed markets, undevelopeed markets might not even have a government capable of rivaling 'Cryptolaw'.


## Emergence of CryptoLaw
- Ethereum -- a Cryptolaw system (ie blockchain code as law)
    - a set of rules administered through the use of smart contracts
    
    
## Blockchain as beyond the reach of law
- Radical libertarian ideological rhetoric associated with Blockchain technology
    - Premise of which is the assumption that the distrubted and decentralised network renders it unregulatable
    
- Similar claims were made regarding the internet. this proved to be a falacy

- As blockchain applications emerge they will become more detatched from the ideological side of blockchain.

## Types of interaction between blockchain code and law
- Hostile Evation -- use of blockchain to evade the limits of the law
- supportive alignment -- use of blockchain to compliment and suppliment conventional law
- Uneasy co-existence -- use of blockchain to avoid the inconvenience and Mutual suspicion.


## Hostile evation
- Use of blockchain tech and decentralised tech to avoid the law.
    - Cyber crime, extortion, tax avoidance
- Legal systems have asserted sovereign authority of law over thse activities.

- Virtual currencies should comply with existing money laundering regulations
- Bitcoin exchanges are treated as regulated intermediaries

## Practical battle for supremacy
- Considerable challenges in applying conventional law enforcment methods against perpetrators

- Conventional law may assert authority over code
    - Can it actually exercise that authority though?
    
- This creates a practical battle between the law and blockchain tech

- Regulatory targets:
    - wallet providers/exchanges
    - And others.
    
## supportive alignment
- Instead of using blockchains to avoid the law -- use to compliment the law.

- Can be used to streamline and enhance the efficiency of compliance.

- Can provide realtime information on thew state of transacitons between users.

- R3's Corda - distributed ledger designed by and for the regulatory industry.

- Not a formal 'battle for supremacy' because they are designed to work together

## uneasy co-existence
- Use vlockchain to avoid the procedural burdens and transaction costs associated with conventional law

- Not trying to subvert the law
    - Just not wanting to bother with the hassel of the clunky and slow system of law that exists.
    
- DAO was an example of this.
    - Developed with the intention of engaging in venture style investements
    - Gives the everyday consumer the opportunity to invest in exciting projects and startups
    
    
## Uneasy co-existence
- Imagnne no hardfork happend after the DAO exploit
    - would the conventional law reached into the transaction? 
- Would a court have refused to take part?

## Uneasy co-existence
- Are blockchain technologies a legitimate or illegitimate attempt to oust conventional law?
- DAOs exist in a regulatory greyzone
    - may not offer liability, protection or accountability guarantees.




# Giovanni Sartor -- Semantics and Pragmatics of self enforcing laws and contracts
## Contracts, logic based smart contracts and blockchain systems
- A project to find a new way to write smart contracts
    - An alternative to Ethereums smart contract system
    
- Aim to reduce the differnece between a smart contract language (like solidity) and human language
    - Increased accessability
- Imperative languages normally used to create smart contracts
- The aim is to move to a more declarative style


## what is a smart contract?
- A program that is used to express an agreement between users
- A program that enacts some kind of transaction or action.

- These contracts can automatically enforce the agreements made.


## What are the problems with these contracts and all contracts?
- Can be very difficult to understand unless familiar with the technology
- Often 'seasoned' with additional formalities.
- This is a problem when trying to expand the reaches of the technology to the general public
    - Trusting of smart contracts will be difficult if there is no understanding.
    
## Defeasable Logic
- A logic represnetation of smart contracts

## Advantages of a declarative language
- Accessability for lawyers and non-technical individuals
- Means that legal authoroties that would normally draft contracts can ensure no illicit activities are being performed.
- The issue of cancelling smart contracts when legally required (like other contracts) still exists.

## Conclusion
- Smart contracts are good
- Need to ensure they are legally compliant.
- Adopt a declaritive language for clarity between stakeholders.






# Panel 2 -- *Blockchain and the future of money*

# Stefan Eich -- *The politics of Cryptocurrencies in historical perspectives*

## Crypto Currencies
- Driven by technology
- Lacking governence
- Cut off from the past (and)

## Is that the right framing?

## Argument
- The forget political disputes over money in the 70s
    - Actively written out of memory by great moderation
    - But resurfaced again with the financial crisis
- In this light cryptocurrences asa political attemt to depoliticise money.

## Hayek, the denationalisation of money (1976)

- Ending of government monopoly of the issue of money
- Decentralisation

## Gunnar Myrdal Oct 1974
- Demands for global democratic reforms
- Proposed 'welfare state' becomes a 'welfare world'
    - Via reformation of monetary systems on a global scale
    
    
## Politics of Disinflation
- After inflation hikes in the 70's/80's
- New polics of disinflation and monetary depoliticization emerged

## The great Moderation 
- Revealed that notion of money existing aside from politics was an illusion

## Financial Crisis
- The emergence of bitcoin after the financial crisis was not a coincidence
- The technology had existed for years
- 6 weeks after the collapse of 'lehsman brothers' (corect spelling) bitcoin emerged

## Bitcoin as an experiemnt of artificial scarcity
- The finite amount of bitcoin
- As more bitcoins became owned, they became more valuble

## Re-politicization
- Just as monetary systems have given rise to calls for decentralised monetary systems
- It has also created a call for more politicised systems.

## In Summary
- Cryptocurrency is intself a political act
    - A political act of depoliticisation
    
- Technology itself is politically neutral
    - Blockchains are politically agnostic, even if its applications aren't 
  
- The creators of a cryptocurrency is infact an act of lawmaking
    - Centralised around their personal political motivations and ideologies.

# Rosa Maria Lastra -- *Pubic Money vs Private Money*

## Fiat Money
- Funcitons of money
    - medium of exchange, store of value, unit of account.
- Governence
    - central bank issue, legal tender, legal counterparty
- Risks
    - theft, fraud, counter-party, inflation
- Consumer appeal
    - good store of value, realtime, reversible
- Foreign exchange
    - costly time
- Centralised clearing
    - paypal, apple pay, cheques
    
## Bitcoin (didnt want to talk about ethereum as well)
- Functions of money
    - medium of exchange, volitile store of value, negligible unit of account
- Governance
    - bitcoin protocol, issuing mining rewards
- Risks
    - medium, interface, malfunction, password (key) loss


## Monetary Sovereignty
- Traditionally
    - The power to issue and distrubute money
    - Monopoly power enjoyed by the state
- New technology
    - Digital currencies, digital payment methods
    - Signify the changing state of monetary sovereignty
  

## theories of money
- The state theory of money is different to the society theory of money are contrasting
    - A state's theory of money is that they decide what constitutes of money
    - The sociatal theory is that money is determined by what has value.
    
## Public money
- Public money is fiat money backed by the state

- Central banks issue all notes in circulation
- Fiat money, inconvertable into gold or other precious materials.
    - The government declares the paper money to be legal tender for the settlement of debts
    
## Private money
- Societal money backed by societal accpetance.
    - Enhanced by reputation/credibility.
    - Currency does not need to be legal tender to exist.
    
## Boom and Busts
- Displacement brings opportunity for profit
    - Herd behavioutr from investor euphoria
- As investors decide to cash out, others follow this movement
    - Causes busts as extensive as the booms.

## Private money and central banking.
- Crypto currencies challenge the status quo of bank monopoly
- Curencies npt backed by any central authority 
    -have a value completely dependant on peoples confidence to use it.


# Claus D. Zimmermann -- *monetary policy in the digital age*
## work in progress, not for citation -- No slides available
## sporadic points
- Interest rates
    - Quantitative easing
- Monetary stability
    - Defined as the stability of domestic prices (different to price stability?).
    
- Cryptograpgic and decentralised currencies have the potential to upheave central banks
    - thus any form of monetary policies.

## Sporadic points
- The IMF defines a series of rules that are used to evaluate the stability of monetary systems and the risks that come with them

- The IMF states that cryptocurrecies will have some of the same risks as the gold Standard

- The drawback of limited amounts of currency in a cryptocurrency doesn't necessarly need to remain so
    - Allowing for the expansion the monetary supply (the issuance of more) would requrie heavy global regulation.
    
## Sporadic points
- IMF warns that wide spread adoption of crypto currencies could see rise to a form of 'great depression' as a result of its limited supply.

- IMF states that it is dificult to see how cryptocurrencies can replace many of the emergency/last resort support functions that centralised banks have.

# Hermann Elender -- *Cryptocurrecny evolution and resiliency of blockchain markets*

## Crypto-Currencies are....
- Neither Crypto, or currency
    - Evil (krugman, 2013)
    - Not evil, too volitile (yermak 2015)
    - insignificant?
    
## Crypto vs corp market cap
- Second larges US enterprise (GOOGL) approx. 588bn
- Ethereum market cap is approx 4.5bn.

- How can these currecies be utilised if they're not worth enought to buy everything?

## Market caps
- Market cap of a traded firm reflects future value
- Crypto currencies reflect the value of the past.

What about other currencies?
- Singapore's currency was less valuble than Ethereum's
- Does that mean singapore does not have a currency?

## Crypto-Currencies are....
- Neither Crypto, or currency
    - Evil (krugman, 2013)
    - Not evil, too volitile (yermak 2015)
    - insignificant?
    
- Money?
    - unit of account??? - other cypto currencis are traded against BTC and ETH. so yes?
    - media of exchange -- sure
    - store of value -- ??? volitle...
        
- Assets
    - market micro structure and economic efficieny.

## Why are Crpyto currencies important?

- The effect that they have in all markets.
- Financial portfolios benefit greatly
- Academic research generated as a side effect.

## Crypto currencies are volatile
- Shown a std-dev graph of other currencies.
- 10% deviation +/- on a day to day basis for Eth (for example)


## Liquidity and resiliency
- How much price impact does trading have on cryptocurrencies?
    - Evolution over time
    - Resiliency to large shocks
    
- The ability to trade at fundamental value is key for economic efficiency

- In the stock market, frequently, liquidty evaporates when shocks hit.
    - How does this look in this drastically different market of cryptocurrencies?
    
## Liquidity measures

- Standard measure -- Amihud measure
    - The sum of returns over the total trading volume over a period.

- Liquid market, large orders are gonna affect pricing
- Not so liquid, large scale will have less effect on prices.

## Crypto vs stocks
- Crypto currencies are orders of magnitude away from standard stocks in liquidity
- DOW market liqudities measure along 0<liquidity<1
- Bitcoin was in the 100s a few years ago, now in 1<liqudity<10 range.

## accounting for regularities
- The time of day, year, month, holidays have regular affects of liquidity
- Need to account for these when getting a true pure liqudity reflection.

## Liquidity shocks
- Bitcoins show almost no relation between the returns and liquidity.
- Even for positive or negative returns. and large shocks.

## Conclusion
- Cryptocurrenceis are a noteworthy asset
- Very fragemented but very integreated
- Liquidity provides a better measure of the matureity than returns or market cap.


# Philipp Hacker - *Corporate Governance for complex cryptocurrencies - regulating blockchain under uncertainty*

## Governance schemes
- Two levels
    - Exact definitions of rules of the game (applying protocol)
    - Lack of rules for changing the rules of the game (updating protocol)
    
## Hard Forks
- Bitcoin hardfork
    - Core dev and miningpool suport older, shorter chain
- Ethereum Hardfork
    - DAO Hack -- essentially fork rewrote the history of the blockchain.
- Bitcoin blocksize debate
    - Discussions between developers, miners, over censorship of the chain
    
    
## Consequences.
- Vulnerability to coalitions of the willing
    - Combine powers, technological, resources and informal leadership
    
- There was anotherone... missed it...


## Complexity theory.
- Simple Order << -- >> Complexity << -- >> Chaos Theory
- Has applicatinos in the financial industry (and crypto currencies.)

## Crypto as complex system
- Dynamic interaction between independent actors over time
    - Self organised and ecentralied feedback driven processes
- Variance within groups
    - Heterogeneity among members of the cryptocurrency ecosystem.
    
- Non-linearity -- elements of order, but unpredictable overtime
    - Lack of governance schemes: fluidity and unpredictability.
    
## Regulatory consequences: a Crypto Governance code?

## Reasons for regulation
- Managing uncertainty
- Complex cryptocurrencies
    - Financial stability -- systemic risk and externality
        - (mandatory)provisions of fincancial market regulation
    - User (or investor) protection -- information and power asymmetries
        - (Soft Law) -- privisions of corporate governance codes.
        
## The governance perspective
- Bringing in spontaneuous and unpredictable interactions
    - Strengthen elements of order and regularity.
- Designation of competencces and procedures
    - Missed what was said here....
    
    
## Advantages of corporate governance
- Implement 'comply or explain'
    - Flexibility and transparency
    - Balancing innovation and user protection
- One set of rules for an international ecosystem
    - solution to puzzels of applicable law, and overlapping regulation.
    
## From corporate to crypto
- Extenal governance (exit)
    - Sale of shares/coins
    - Hard fork/corporate controle
- Internal governance (voice)
    - Directors/miners





# Panel 3 -- *Blockchain and the future of banking and finance*



# Rohan Grey -- *Banking Under A digital Money Fiat*

## Modern Money
- The state comes in first as all authority of law -- Money Stuff.

## Money in the 21st Century
- Buckminster Fuller -- To make change... build something... make the prior obsolete

(find the full quote later)


## DFC Dollar (Digital Fiat currency)
- Digital Token via compatible payment networks
- government issues, legal tender, tax acceptable
- Guaranteed Principle, Zero or +ve interest/maturity
- Superconvertible
    - can convert to and from other currencies.
- Bearer instrument or registered account

## Coins vs Centeral Bank Notes
- Bearer instruments -- who holds them, owns them

coins|Central Bank notes
----|--------
Mint issues | central bank issues

## Securities
- Treasury securities are issued by treasuries
- ceneral bank securities are issued by central banks

## MetaMoney
- Re-Organises different aspects of a fiat money
- This is the superconvertability at play
- moving from food stamp aspect to student debt aspect
- same process/ease as moving funds from personal acount to an ISA or something else


# Registered account or bearer instrument?
- Visible Ledger -- everyone holds a DFC account
    - similar to equadorian model of epayment methods.
    
- invisible ledger -- a distribued not decentralised approach
    - Note to self. this is pretty much what happens now. just not with blockchains but with normal Databases.
    - the difference i guess is down to the Compartmentalised versions of the DFC
    
## DFC System
- Eliminates most of the uses that a bank has
- Credit is the only function that remains

## Banks as Fiscal Agents

## Regulatory implications
- Similar to unlimited deposit insurance
- Do one thing well: underwriting
- Asset-side discipline: collateral quality.

## Challenges
- Private credit vs public investment
- regulated vs shadow finance
- the 'veil' of money and banking

## The End 






# Iris Chiu -- *A New Era in fintech payment innovations? A perspective from the institutions and regulation of payment systems*

## Payment Innovatikons
- Focus on New payment interfaces
    - Apple Pay, Amaozon 1-click, etc
    
## Payment involves intermediaries
- when parties are not in the same location
    - physcial cash is not used
    - payment is done via transfers through a 3rd party
    
- Banks have arisen as the lead of intermediaries
    - accounts are managed at a central bank

## Payment Systems
2 types of systems
- Large value payment systems feature bank domination
    - central bank based clearing and settlement
- Retail payment systems
    - also bank dominated -- front end clearing and settlement at central bank
    - not a bad thing -- consumer protection is possible as a result
    
## Complaints
- retail systems recieve numerous complaints
    - speed is poor
    - uncompetitive
    - charges and fees
    - old fashioned interfaces.
    
- commercial innovation is observed with the rise of fintech
    - but have consumer outcomes actually improved?
    
## Payment interfaces     
- Seek to improve Consumer experience
- Speed and ease of Use
- Still don't penetrate to the level of clearance and settlement at central banks
- require storing access to your bank accounts on various devices.


## Payment interface innovations
- M-PESA A True Alternative to standard settlement and clearing
- Safari.com?

## Reflections
- non-penetration of payment interfaces means limited changes to customer outcomes
- charges and fees may remain stubborn
- With innovation comes new security risks
    - its difficult to get 100% coverage of new technology
    - Exploits will eventually be found (DAO hack in Ethereum)
- Cryptocurrencies have their uses.
    - unlikely to see them penetrate to the level needed to really have an impact
    









# Alexandros Seretakis -- *Blockchain, Securities markets and central banking*

## Experimenting with Distributed Ledger Technology (DLT)
-  ECB and bank pof japan
    - research project regarding the use of the technology for market infrastructure
- NASDAQ
    - NASDAQ private market
- Overstock
    - issuance of private digital bonds
    
    
## The Promise
- No need for central validation systems
- Shared Database
- Protecion against assets being transferred twice
- Transaction permanence and irreversability
- Transparency
- 24/7 Operation
- DLT and Smart Contracts
- Permanent and Time Stampted

## Securities Markets
- Transparency of Securities ownership (shares, etc.)
- Compression of settlment cycles
    - lowering counterparty settlement risk, enhancing liquidity
- instant settlement
    - elimination of counterparty risk
    - clearing made redundant (cash spot transactions)
    
- Smart contracts
    - automation of a variety of processes
    - Netting and Margining
    
## Central Banking
- Technology is not ready for mass adoption
    - doesn't yet meet the safety and security standards offered by centralised banks
- should banks accept direct deposits from nonbank institutions?





# Peter McBurney -- *Verification and Validation of smart contracts: challenges for law and Computer Science*

## Web vs Blockchain
- The web was the last technology advancement widescale disruption of all areas
- Blockchain is doing the same sort of exciting disruptions

## Stateful Shared State
- Al nodes on a distributed ledger aggree pon the values of the variavble on the ledger
    - they have a share state
- the ledger also preserves past states
    - the protocol is stateful
    - in contrast, HTTP is Stateless


Distributed Ledgers have Stateful Shared State.

## DLTs -- Evolving Thinking over 2 years
DLTs are appropriate for:
- Cryptocurrencies
- currency transactions
- transactions involving the exchanges of assets
    - chains of custory
- records of information
    - medical records, personal identity, company records
- primises and commitments
    - futures contracts, trade flows
    
## Comparison of WWW and Blockchains
Web
- Easy Discemination of information
- Information Society
- Advertising, e-Commerse, DB access
- Business PRocess Engineering within organisations

Blockchain and DLT
- Agrement on shared information and action
- Stateful shared state
- Joint-Action-Society
- Identity Records, Chains of commerse, insurance
- Business PRocess Engineering Accross Organisations.


# Aaron J. Wright -- *The promises and regulatory challenges of decentralised organiseations*

## Blockchain characteristics
- Global and Transnational
- Resilient and tamper resistan
- transparant and Non-repudiable records
- pseudonyms
- incentive mechanisms

## Blockchain Enables:
- Global Disgital Currencies
- Highly resilieent authenticated, tamper resistant registries
- the execution of computational processes that can be autonomous

## coo-ordination of social and economic activity in a decentralised way.

## tamper resistant registreis includes voting
  - Privacy is not a concern here
  - ^^^ this required clarification 
  
## Tamper Resistet registries for stock certificates

## Smart contracts
- facilitate payments
- transfer assets, including dividends, profit interests
- tally votes
- Escrow (for exchange of goods/services.)

## Theoretical Framework
- Blockchains can reduce (not eliminate) organisational frictions
- Enforcement mechanisms reduce risk of opportunistic behaviour






# Panel 4 -- *Blockchain and the future of Finteck Regulation*

# Michael Jacobides -- *Transformation of corporate scope in US Banks: patterns and performance implications*

## This was a general finance presentation
- covered the composition of banking corporations.

## How predictable are Financial crises? (Not a slide, my own questions)
- Adapted Z score used to predict a bank going bust
- some speculation regarding what would happen if another financial crisis occurs
    - or if a major bank fails
- would this push a people to move their finances into cryptocurrencies like Ether, would this have a detrimental effect overall?





# Pietro Ortolani -- *Is Bitcoin Disruptng the Law? A tale of Jurisdiction, Currency and Sovereignty*

## Nationalism/Transnationalism tension
- nationalists oppose the erosion of tradition
- transnationalists will support the progression of cryptocurrency ideologies

## Digical currency illusions
- Technology and Ideology of the cryptocurrency are distinct
- once released, the developers of a technology will have no controll of the associated ideology

## Assessing the impact of the technology
- Impact on the centrality of state courts in:
    - the administration of justice
    
- Impact on the monopoly of the state over:
    - something something something... missed it.
    
    
## The Feedback Loop
- State: Law -> courts -> procedure -> currency -> Law
- how do you seize assets on a blockchain?

## Bitcoin in US cases
- Bitcoin transactions rose by 100,000s over the years
- amount of court cases/ criminal cases mentioning bitcoin is very small
- some criminal, most civil, still minimal (17 in 2016)

## assessment
- private adjudication currently prevail over court litigation
- plaintiff inactivity could play a role
- incentives for high value cases may be different.

## enforcement of decisions
- the state perspective: Balancing
- The smart contract perspective: Automation

## A new normative framework
- standard setting at the transnational level
- balancing as an overarching goal
- mor cooperation between technology and dispute resolution experts




# Angela Walch -- *The Fiduciaries of Public Blockchains*

## Summary - anyone working on an open source project is a 'fiduciary'


# Georgios Dimitropoulos -- *Global Currencies and Domestic Regulation: embedding through enabling.*

## Regulatory approaches to Cryptocurrencies
Command And Control
- China: Central bank of china and other agencies gave a 'notice on precautions on the payment of cryptocurrencies'
    - banks in china cannot handle them

- United Arab Emirates: all virtual currencies and any transactions are prohuibuted
    - announce Cryptocurrencies are not applicable to this legislation


## Regulatory approaches to Cryptocurrencies
Intermediate approaches
- Warnings
    - france
    - EBA
    - US
    
- Taxation
    - IRS: For federal tax purposes, virtual currency is treated as property.
    
## Legal Nature of Cryptocurrencies
- Different jurisdictions take idfferent views
Some view it as:
a) money
b) commodity
c) technology
or any combination of.

## The legal nature of cryptocurrencies.
Global Currency as Currency
Money
- US: Guidance specifying that decentralised currencies should comply with money laundering regulations
- Germany: Not a form of legal tender, but are legally binding financial instruments that are similar to foreign currencies in that they are a form of units of account.
- France: They may be percieved as money, and cryptocurrency intermediaries may quialify as financial intermediaries.
- UK: HMRC -- Cryptocurrency related activities are not subject to VAT as they are considered a form of Money.
- EU: implicit and explicit recognition of cryptocurrency as a form of money


## The legal nature of cryptocurrencies.
Commodity:
- China: bitcoins can be exchanged between citizins without the involvement of banks
- US: its a commodity....

## THe Duel nature of Cryptocurrencies
- Regulation as currency
    - restrictive approaches when percieved as money or commodity
    
- regulation as technology
    - UK AUS etc, promote and don't restrict it as a technology
    - FinTech + FCA - Innovation hub, regulatory Sandbox
    
    - AUSL: ASIC FinTech Class exemption.
    
## Embedding through enabling
- Peril 1: More Finance:
    - constraining conventional finacnce, whilst at the same time enabling finTech Products
    
- Peril2: Clash of agencies


## Mitigating the issues:
- Combine the restricting and fascilitating aproaches.

- Regulate new intermediaries.
    - US: 'BitLiscence' for virutal currency business activity.
    


# Jonathan Greenacre -- *Fintech in Africa: The regulation of mobile money.*

##

